seed: 42
batch_size: 6
epochs: 20
lr: 0.001
num_workers: 32

# DDP settings
world_size: 7
dist_backend: "nccl"
dist_url: "env://"

# CSV 모델 경로
csv_file: "./ff++_c23_landmark.csv"


# Model config
# config/config.yaml
model:
  image_size: 224
  patch_size: 32
  hidden_dim: 768
  num_classes: 2


# WandB
wandb_project: "FacePartProject"
wandb_entity: ""
wandb_run_name: "landmark_exp"
