seed: 42
batch_size: 4
epochs: 5
lr: 0.0001
num_workers: 2

# DDP settings
world_size: 1
dist_backend: "nccl"
dist_url: "tcp://127.0.0.1:23456"

# CSV, dlib 모델 경로
csv_file: "./ff++_c23.csv"
shape_predictor_path: "./shape_predictor_68_face_landmarks.dat"

# Model config
model:
  image_size: 224
  patch_size: 16
  hidden_dim: 768
  num_classes: 2

# WandB
wandb_project: "FacePartProject"
wandb_entity: ""
wandb_run_name: "landmark_exp"
